//! The per-model configuration tables.
//!
//! Generated by hand from the facts named in the crate documentation, and
//! checked by the tests below rather than trusted. Nothing here is authored
//! expression: every number is an address in a piece of hardware.

use super::config::{ConfigItem, ConfigSet, Descriptor};

/// Configuration table `gen2a`.
pub(super) const GEN2A: ConfigSet = ConfigSet {
    param_buf_addr: 0x0000,
    items: &[
        (
            ConfigItem::LevelSwitch,
            Descriptor {
                offset: 0x007c,
                size_bits: 8,
                activate: 7,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::LineOutVolume,
            Descriptor {
                offset: 0x0034,
                size_bits: 16,
                activate: 1,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::MuteSwitch,
            Descriptor {
                offset: 0x005c,
                size_bits: 8,
                activate: 1,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::PadSwitch,
            Descriptor {
                offset: 0x0084,
                size_bits: 8,
                activate: 8,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::StandaloneSwitch,
            Descriptor {
                offset: 0x008d,
                size_bits: 8,
                activate: 6,
                via_param_buf: false,
            },
        ),
    ],
};

/// Configuration table `gen2b`.
pub(super) const GEN2B: ConfigSet = ConfigSet {
    param_buf_addr: 0x0000,
    items: &[
        (
            ConfigItem::DimMute,
            Descriptor {
                offset: 0x0031,
                size_bits: 8,
                activate: 2,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::LevelSwitch,
            Descriptor {
                offset: 0x007c,
                size_bits: 8,
                activate: 7,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::LineOutVolume,
            Descriptor {
                offset: 0x0034,
                size_bits: 16,
                activate: 1,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::MasterVolume,
            Descriptor {
                offset: 0x0076,
                size_bits: 16,
                activate: 0,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::MuteSwitch,
            Descriptor {
                offset: 0x005c,
                size_bits: 8,
                activate: 1,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::PadSwitch,
            Descriptor {
                offset: 0x0084,
                size_bits: 8,
                activate: 8,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::StandaloneSwitch,
            Descriptor {
                offset: 0x008d,
                size_bits: 8,
                activate: 6,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::SwHwSwitch,
            Descriptor {
                offset: 0x0066,
                size_bits: 8,
                activate: 3,
                via_param_buf: false,
            },
        ),
    ],
};

/// Configuration table `gen3a`.
pub(super) const GEN3A: ConfigSet = ConfigSet {
    param_buf_addr: 0x0000,
    items: &[
        (
            ConfigItem::AirSwitch,
            Descriptor {
                offset: 0x0009,
                size_bits: 1,
                activate: 8,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::DirectMonitor,
            Descriptor {
                offset: 0x0007,
                size_bits: 8,
                activate: 4,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::LevelSwitch,
            Descriptor {
                offset: 0x0008,
                size_bits: 1,
                activate: 7,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::MsdSwitch,
            Descriptor {
                offset: 0x0004,
                size_bits: 8,
                activate: 6,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::PhantomPersistence,
            Descriptor {
                offset: 0x0005,
                size_bits: 8,
                activate: 6,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::PhantomSwitch,
            Descriptor {
                offset: 0x0006,
                size_bits: 8,
                activate: 3,
                via_param_buf: false,
            },
        ),
    ],
};

/// Configuration table `gen3b`.
pub(super) const GEN3B: ConfigSet = ConfigSet {
    param_buf_addr: 0x0000,
    items: &[
        (
            ConfigItem::AirSwitch,
            Descriptor {
                offset: 0x008c,
                size_bits: 8,
                activate: 8,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::LevelSwitch,
            Descriptor {
                offset: 0x007c,
                size_bits: 8,
                activate: 7,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::LineOutVolume,
            Descriptor {
                offset: 0x0034,
                size_bits: 16,
                activate: 1,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::MsdSwitch,
            Descriptor {
                offset: 0x009d,
                size_bits: 8,
                activate: 6,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::MuteSwitch,
            Descriptor {
                offset: 0x005c,
                size_bits: 8,
                activate: 1,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::PadSwitch,
            Descriptor {
                offset: 0x0084,
                size_bits: 8,
                activate: 8,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::PhantomPersistence,
            Descriptor {
                offset: 0x009e,
                size_bits: 8,
                activate: 6,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::PhantomSwitch,
            Descriptor {
                offset: 0x009c,
                size_bits: 1,
                activate: 8,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::StandaloneSwitch,
            Descriptor {
                offset: 0x0095,
                size_bits: 8,
                activate: 6,
                via_param_buf: false,
            },
        ),
    ],
};

/// Configuration table `gen3c`.
pub(super) const GEN3C: ConfigSet = ConfigSet {
    param_buf_addr: 0x0000,
    items: &[
        (
            ConfigItem::AirSwitch,
            Descriptor {
                offset: 0x008c,
                size_bits: 8,
                activate: 8,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::DimMute,
            Descriptor {
                offset: 0x0031,
                size_bits: 8,
                activate: 2,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::LevelSwitch,
            Descriptor {
                offset: 0x007c,
                size_bits: 8,
                activate: 7,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::LineOutVolume,
            Descriptor {
                offset: 0x0034,
                size_bits: 16,
                activate: 1,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::MasterVolume,
            Descriptor {
                offset: 0x0076,
                size_bits: 16,
                activate: 0,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::MonitorOtherEnable,
            Descriptor {
                offset: 0x00a0,
                size_bits: 1,
                activate: 10,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::MonitorOtherSwitch,
            Descriptor {
                offset: 0x009f,
                size_bits: 1,
                activate: 10,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::MsdSwitch,
            Descriptor {
                offset: 0x009d,
                size_bits: 8,
                activate: 6,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::MuteSwitch,
            Descriptor {
                offset: 0x005c,
                size_bits: 8,
                activate: 1,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::PadSwitch,
            Descriptor {
                offset: 0x0084,
                size_bits: 8,
                activate: 8,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::PhantomPersistence,
            Descriptor {
                offset: 0x009e,
                size_bits: 8,
                activate: 6,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::PhantomSwitch,
            Descriptor {
                offset: 0x009c,
                size_bits: 1,
                activate: 8,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::SpdifMode,
            Descriptor {
                offset: 0x0094,
                size_bits: 8,
                activate: 6,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::StandaloneSwitch,
            Descriptor {
                offset: 0x0095,
                size_bits: 8,
                activate: 6,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::SwHwSwitch,
            Descriptor {
                offset: 0x0066,
                size_bits: 8,
                activate: 3,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::TalkbackMap,
            Descriptor {
                offset: 0x00b0,
                size_bits: 16,
                activate: 10,
                via_param_buf: false,
            },
        ),
    ],
};

/// Configuration table `vocaster`.
pub(super) const VOCASTER: ConfigSet = ConfigSet {
    param_buf_addr: 0x01bc,
    items: &[
        (
            ConfigItem::AgHotTarget,
            Descriptor {
                offset: 0x00c1,
                size_bits: 8,
                activate: 29,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::AutogainStatus,
            Descriptor {
                offset: 0x01c2,
                size_bits: 8,
                activate: 0,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::AutogainSwitch,
            Descriptor {
                offset: 0x01c0,
                size_bits: 8,
                activate: 19,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::BluetoothVolume,
            Descriptor {
                offset: 0x00bf,
                size_bits: 8,
                activate: 28,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::CompressorParams,
            Descriptor {
                offset: 0x01c8,
                size_bits: 32,
                activate: 23,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::DspSwitch,
            Descriptor {
                offset: 0x01c4,
                size_bits: 8,
                activate: 22,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::InputGain,
            Descriptor {
                offset: 0x009f,
                size_bits: 8,
                activate: 21,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::InputMuteSwitch,
            Descriptor {
                offset: 0x01be,
                size_bits: 8,
                activate: 17,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::MsdSwitch,
            Descriptor {
                offset: 0x009d,
                size_bits: 8,
                activate: 6,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::PeqFltParams,
            Descriptor {
                offset: 0x0250,
                size_bits: 32,
                activate: 27,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::PeqFltSwitch,
            Descriptor {
                offset: 0x0084,
                size_bits: 32,
                activate: 27,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::PhantomSwitch,
            Descriptor {
                offset: 0x009c,
                size_bits: 1,
                activate: 20,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::PrecompFltParams,
            Descriptor {
                offset: 0x0200,
                size_bits: 32,
                activate: 27,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::PrecompFltSwitch,
            Descriptor {
                offset: 0x007c,
                size_bits: 32,
                activate: 27,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::SpHpMute,
            Descriptor {
                offset: 0x00ab,
                size_bits: 8,
                activate: 10,
                via_param_buf: false,
            },
        ),
    ],
};

/// Configuration table `gen4_solo`.
pub(super) const GEN4_SOLO: ConfigSet = ConfigSet {
    param_buf_addr: 0x00d8,
    items: &[
        (
            ConfigItem::AirSwitch,
            Descriptor {
                offset: 0x003e,
                size_bits: 8,
                activate: 11,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::DirectMonitor,
            Descriptor {
                offset: 0x0108,
                size_bits: 8,
                activate: 12,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::DirectMonitorGain,
            Descriptor {
                offset: 0x0232,
                size_bits: 16,
                activate: 26,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::LevelSwitch,
            Descriptor {
                offset: 0x003d,
                size_bits: 8,
                activate: 10,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::MsdSwitch,
            Descriptor {
                offset: 0x0047,
                size_bits: 8,
                activate: 4,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::PcmInputSwitch,
            Descriptor {
                offset: 0x0206,
                size_bits: 8,
                activate: 25,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::PhantomSwitch,
            Descriptor {
                offset: 0x0046,
                size_bits: 8,
                activate: 9,
                via_param_buf: true,
            },
        ),
    ],
};

/// Configuration table `gen4_solo_2417`.
pub(super) const GEN4_SOLO_2417: ConfigSet = ConfigSet {
    param_buf_addr: 0x00d8,
    items: &[
        (
            ConfigItem::AirSwitch,
            Descriptor {
                offset: 0x003e,
                size_bits: 8,
                activate: 11,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::DirectMonitor,
            Descriptor {
                offset: 0x0108,
                size_bits: 8,
                activate: 12,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::DirectMonitorGain,
            Descriptor {
                offset: 0x0232,
                size_bits: 16,
                activate: 26,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::FpBrightness,
            Descriptor {
                offset: 0x0243,
                size_bits: 8,
                activate: 27,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::FpSleepTime,
            Descriptor {
                offset: 0x0248,
                size_bits: 32,
                activate: 29,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::LevelSwitch,
            Descriptor {
                offset: 0x003d,
                size_bits: 8,
                activate: 10,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::MsdSwitch,
            Descriptor {
                offset: 0x0047,
                size_bits: 8,
                activate: 4,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::PcmInputSwitch,
            Descriptor {
                offset: 0x0206,
                size_bits: 8,
                activate: 25,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::PhantomSwitch,
            Descriptor {
                offset: 0x0046,
                size_bits: 8,
                activate: 9,
                via_param_buf: true,
            },
        ),
    ],
};

/// Configuration table `gen4_2i2`.
pub(super) const GEN4_2I2: ConfigSet = ConfigSet {
    param_buf_addr: 0x00fc,
    items: &[
        (
            ConfigItem::AgMeanTarget,
            Descriptor {
                offset: 0x0131,
                size_bits: 8,
                activate: 29,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::AgPeakTarget,
            Descriptor {
                offset: 0x0132,
                size_bits: 8,
                activate: 30,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::AirSwitch,
            Descriptor {
                offset: 0x003e,
                size_bits: 8,
                activate: 15,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::AutogainStatus,
            Descriptor {
                offset: 0x0137,
                size_bits: 8,
                activate: 0,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::AutogainSwitch,
            Descriptor {
                offset: 0x0135,
                size_bits: 8,
                activate: 10,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::DirectMonitor,
            Descriptor {
                offset: 0x014a,
                size_bits: 8,
                activate: 16,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::DirectMonitorGain,
            Descriptor {
                offset: 0x02a0,
                size_bits: 16,
                activate: 36,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::InputGain,
            Descriptor {
                offset: 0x004b,
                size_bits: 8,
                activate: 12,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::InputLinkSwitch,
            Descriptor {
                offset: 0x014e,
                size_bits: 8,
                activate: 18,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::InputSelectSwitch,
            Descriptor {
                offset: 0x014b,
                size_bits: 8,
                activate: 17,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::LevelSwitch,
            Descriptor {
                offset: 0x003c,
                size_bits: 8,
                activate: 13,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::MsdSwitch,
            Descriptor {
                offset: 0x0049,
                size_bits: 8,
                activate: 4,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::PhantomSwitch,
            Descriptor {
                offset: 0x0048,
                size_bits: 8,
                activate: 11,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::SafeSwitch,
            Descriptor {
                offset: 0x0147,
                size_bits: 8,
                activate: 14,
                via_param_buf: true,
            },
        ),
    ],
};

/// Configuration table `gen4_2i2_2417`.
pub(super) const GEN4_2I2_2417: ConfigSet = ConfigSet {
    param_buf_addr: 0x00fc,
    items: &[
        (
            ConfigItem::AgMeanTarget,
            Descriptor {
                offset: 0x0131,
                size_bits: 8,
                activate: 29,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::AgPeakTarget,
            Descriptor {
                offset: 0x0132,
                size_bits: 8,
                activate: 30,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::AirSwitch,
            Descriptor {
                offset: 0x003e,
                size_bits: 8,
                activate: 15,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::AutogainStatus,
            Descriptor {
                offset: 0x0137,
                size_bits: 8,
                activate: 0,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::AutogainSwitch,
            Descriptor {
                offset: 0x0135,
                size_bits: 8,
                activate: 10,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::DirectMonitor,
            Descriptor {
                offset: 0x014a,
                size_bits: 8,
                activate: 16,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::DirectMonitorGain,
            Descriptor {
                offset: 0x02a4,
                size_bits: 16,
                activate: 36,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::FpBrightness,
            Descriptor {
                offset: 0x02c7,
                size_bits: 8,
                activate: 37,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::FpSleepTime,
            Descriptor {
                offset: 0x02cc,
                size_bits: 32,
                activate: 39,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::InputGain,
            Descriptor {
                offset: 0x004b,
                size_bits: 8,
                activate: 12,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::InputLinkSwitch,
            Descriptor {
                offset: 0x014e,
                size_bits: 8,
                activate: 18,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::InputSelectSwitch,
            Descriptor {
                offset: 0x014b,
                size_bits: 8,
                activate: 17,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::LevelSwitch,
            Descriptor {
                offset: 0x003c,
                size_bits: 8,
                activate: 13,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::MsdSwitch,
            Descriptor {
                offset: 0x0049,
                size_bits: 8,
                activate: 4,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::PhantomSwitch,
            Descriptor {
                offset: 0x0048,
                size_bits: 8,
                activate: 11,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::SafeSwitch,
            Descriptor {
                offset: 0x0147,
                size_bits: 8,
                activate: 14,
                via_param_buf: true,
            },
        ),
    ],
};

/// Configuration table `gen4_4i4`.
pub(super) const GEN4_4I4: ConfigSet = ConfigSet {
    param_buf_addr: 0x0130,
    items: &[
        (
            ConfigItem::AgMeanTarget,
            Descriptor {
                offset: 0x013a,
                size_bits: 8,
                activate: 23,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::AgPeakTarget,
            Descriptor {
                offset: 0x013b,
                size_bits: 8,
                activate: 24,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::AirSwitch,
            Descriptor {
                offset: 0x0050,
                size_bits: 8,
                activate: 15,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::AutogainStatus,
            Descriptor {
                offset: 0x0140,
                size_bits: 8,
                activate: 0,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::AutogainSwitch,
            Descriptor {
                offset: 0x013e,
                size_bits: 8,
                activate: 10,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::HeadphoneVolume,
            Descriptor {
                offset: 0x003a,
                size_bits: 16,
                activate: 0,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::InputGain,
            Descriptor {
                offset: 0x005e,
                size_bits: 8,
                activate: 12,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::InputLinkSwitch,
            Descriptor {
                offset: 0x0156,
                size_bits: 8,
                activate: 17,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::InputSelectSwitch,
            Descriptor {
                offset: 0x0153,
                size_bits: 8,
                activate: 16,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::LevelSwitch,
            Descriptor {
                offset: 0x004e,
                size_bits: 8,
                activate: 13,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::MasterVolume,
            Descriptor {
                offset: 0x0032,
                size_bits: 16,
                activate: 0,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::MsdSwitch,
            Descriptor {
                offset: 0x005c,
                size_bits: 8,
                activate: 4,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::PhantomSwitch,
            Descriptor {
                offset: 0x005a,
                size_bits: 8,
                activate: 11,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::PowerExt,
            Descriptor {
                offset: 0x0168,
                size_bits: 8,
                activate: 0,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::PowerLow,
            Descriptor {
                offset: 0x016d,
                size_bits: 8,
                activate: 0,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::SafeSwitch,
            Descriptor {
                offset: 0x0150,
                size_bits: 8,
                activate: 14,
                via_param_buf: true,
            },
        ),
    ],
};

/// Configuration table `gen4_4i4_2417`.
pub(super) const GEN4_4I4_2417: ConfigSet = ConfigSet {
    param_buf_addr: 0x0130,
    items: &[
        (
            ConfigItem::AgMeanTarget,
            Descriptor {
                offset: 0x013a,
                size_bits: 8,
                activate: 23,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::AgPeakTarget,
            Descriptor {
                offset: 0x013b,
                size_bits: 8,
                activate: 24,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::AirSwitch,
            Descriptor {
                offset: 0x0050,
                size_bits: 8,
                activate: 15,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::AutogainStatus,
            Descriptor {
                offset: 0x0140,
                size_bits: 8,
                activate: 0,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::AutogainSwitch,
            Descriptor {
                offset: 0x013e,
                size_bits: 8,
                activate: 10,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::FpBrightness,
            Descriptor {
                offset: 0x03a9,
                size_bits: 8,
                activate: 36,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::FpSleepTime,
            Descriptor {
                offset: 0x03ac,
                size_bits: 32,
                activate: 38,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::HeadphoneVolume,
            Descriptor {
                offset: 0x003a,
                size_bits: 16,
                activate: 0,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::InputGain,
            Descriptor {
                offset: 0x005e,
                size_bits: 8,
                activate: 12,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::InputLinkSwitch,
            Descriptor {
                offset: 0x0156,
                size_bits: 8,
                activate: 17,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::InputSelectSwitch,
            Descriptor {
                offset: 0x0153,
                size_bits: 8,
                activate: 16,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::LevelSwitch,
            Descriptor {
                offset: 0x004e,
                size_bits: 8,
                activate: 13,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::MasterVolume,
            Descriptor {
                offset: 0x0032,
                size_bits: 16,
                activate: 0,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::MsdSwitch,
            Descriptor {
                offset: 0x005c,
                size_bits: 8,
                activate: 4,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::PhantomSwitch,
            Descriptor {
                offset: 0x005a,
                size_bits: 8,
                activate: 11,
                via_param_buf: true,
            },
        ),
        (
            ConfigItem::PowerExt,
            Descriptor {
                offset: 0x0168,
                size_bits: 8,
                activate: 0,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::PowerLow,
            Descriptor {
                offset: 0x016d,
                size_bits: 8,
                activate: 0,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::SafeSwitch,
            Descriptor {
                offset: 0x0150,
                size_bits: 8,
                activate: 14,
                via_param_buf: true,
            },
        ),
    ],
};

/// Configuration table `clarett`.
pub(super) const CLARETT: ConfigSet = ConfigSet {
    param_buf_addr: 0x0000,
    items: &[
        (
            ConfigItem::AirSwitch,
            Descriptor {
                offset: 0x0095,
                size_bits: 8,
                activate: 8,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::DimMute,
            Descriptor {
                offset: 0x0031,
                size_bits: 8,
                activate: 2,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::LevelSwitch,
            Descriptor {
                offset: 0x007c,
                size_bits: 8,
                activate: 7,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::LineOutVolume,
            Descriptor {
                offset: 0x0034,
                size_bits: 16,
                activate: 1,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::MasterVolume,
            Descriptor {
                offset: 0x0076,
                size_bits: 16,
                activate: 0,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::MuteSwitch,
            Descriptor {
                offset: 0x005c,
                size_bits: 8,
                activate: 1,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::SpdifMode,
            Descriptor {
                offset: 0x009e,
                size_bits: 8,
                activate: 4,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::StandaloneSwitch,
            Descriptor {
                offset: 0x008d,
                size_bits: 8,
                activate: 6,
                via_param_buf: false,
            },
        ),
        (
            ConfigItem::SwHwSwitch,
            Descriptor {
                offset: 0x0066,
                size_bits: 8,
                activate: 3,
                via_param_buf: false,
            },
        ),
    ],
};
